{
	"name": "Zigbee2Mqtt",
	"version": "1.0.0",
	"icon": "far fa-signal-stream",
	"category": "automation",
	"author": "Psychokiller1888",
	"maintainers": ["maxbachmann"],
	"desc": "Have your zigbee devices communicate with alice directly over mqtt",
	"aliceMinVersion": "1.0.0-a6",
	"pipRequirements": [],
	"systemRequirements": [
		"make",
		"g++",
		"gcc"
	],
	"script": "zigbee2mqtt.sh",
	"conditions": {}
}
