{
    "name": "Zigbee2Mqtt",
    "version": "1.2.15",
    "icon": "far fa-signal-stream",
    "category": "automation",
    "author": "Psychokiller1888",
    "maintainers": ["philipp2310"],
    "desc": "Have your zigbee devices communicate with alice directly over mqtt",
    "aliceMinVersion": "1.0.0-rc1",
    "pipRequirements": [],
    "systemRequirements": [
        "make",
        "g++",
        "gcc"
    ],
    "script": "zigbee2mqtt.sh",
    "conditions": {}
}
